// This file is auto-generated by @hey-api/openapi-ts

export type LoginUserInput = {
    email: string;
    password: string;
};

export type UsersControllerCreateUserResponse = unknown;

export type AuthControllerLoginData = {
    requestBody: LoginUserInput;
};

export type AuthControllerLoginResponse = unknown;

export type AuthControllerRefreshTokenResponse = unknown;

export type HealthControllerCheckHealthResponse = {
    status?: string;
    info?: {
        [key: string]: {
            status?: string;
            [key: string]: (string) | undefined;
        };
    } | null;
    error?: {
        [key: string]: {
            status?: string;
            [key: string]: (string) | undefined;
        };
    } | null;
    details?: {
        [key: string]: {
            status?: string;
            [key: string]: (string) | undefined;
        };
    };
};

export type $OpenApiTs = {
    '/api/users/create': {
        post: {
            res: {
                201: unknown;
            };
        };
    };
    '/api/auth': {
        post: {
            req: AuthControllerLoginData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/api/health': {
        get: {
            res: {
                /**
                 * The Health Check is successful
                 */
                200: {
                    status?: string;
                    info?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    } | null;
                    error?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    } | null;
                    details?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    };
                };
                /**
                 * The Health Check is not successful
                 */
                503: {
                    status?: string;
                    info?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    } | null;
                    error?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    } | null;
                    details?: {
                        [key: string]: {
                            status?: string;
                            [key: string]: (string) | undefined;
                        };
                    };
                };
            };
        };
    };
};